export const USER_ISAUTHENTICATED_REQUEST = "USER IS AUTHENTICATED REQUEST";
export const USER_ISAUTHENTICATED_SUCCESS = "USER IS AUTHENTICATED SUCCESS";
export const USER_ISAUTHENTICATED_FAILURE = "USER IS AUTHENTICATED FAILURE";
